[program:wsevent]
command=node /home/dmoj/site/websocket/daemon.js
directory=/home/dmoj/site/websocket
user=dmoj
group=dmoj
stdout_logfile=/tmp/wsevent.stdout.log
stderr_logfile=/tmp/wsevent.stderr.log
autostart=true
autorestart=true