# Generated by Django 4.2.30 on 2026-09-20 05:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0154_clue_oj_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='is_ntucoder',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is NTUCoder problem'),
        ),
        migrations.AddField(
            model_name='problem',
            name='ntucoder_code',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='NTUCoder problem code'),
        ),
        migrations.AddField(
            model_name='problem',
            name='ntucoder_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='NTUCoder problem ID'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ntucoder_cookie',
            field=models.TextField(blank=True, default='', verbose_name='NTUCoder session cookie'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ntucoder_email',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='NTUCoder email'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ntucoder_password',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='NTUCoder password'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ntucoder_username',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='NTUCoder username'),
        ),
        migrations.AddField(
            model_name='submission',
            name='ntucoder_submission_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='NTUCoder submission ID'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='code',
            field=models.CharField(help_text='A short, unique code for the problem, used in the URL after /problem/', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9_]+$', 'Problem code must be ^[a-z0-9_]+$')], verbose_name='problem code'),
        ),
    ]
