# Generated by Django 4.2.30 on 2026-09-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0155_problem_is_ntucoder_problem_ntucoder_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='is_ltpt',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is LTPT problem'),
        ),
        migrations.AddField(
            model_name='problem',
            name='ltpt_code',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='LTPT problem code'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ltpt_cookie',
            field=models.TextField(blank=True, default='', verbose_name='LTPT session cookie'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ltpt_password',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='LTPT password'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ltpt_username',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='LTPT username'),
        ),
        migrations.AddField(
            model_name='submission',
            name='ltpt_submission_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='LTPT submission ID'),
        ),
    ]
